### ISSUE TITLE
Ionic mobile app - Error: Manifest functionality disabled

### ISSUE THREAD

**Issue by prabhashibuddhima** [aron123/node-barion#34]
Hi, I'm building my ionic app with a payment gateway. I'm trying to use Barion and I'm getting the following error saying that Manifest functionality is disabled. How can I get through this?

![image](https://user-images.githubusercontent.com/29029785/93694947-b24bc480-fac6-11ea-8452-976c6470071e.png)

**Comment by aron123** [comment]
I think, that for your ionic application, joi's browser version is installed as a sub dependency, which does not includes `describe` function of Schema definitions (https://github.com/sideway/joi/issues/2198).

You can try to switch off `ValidateModels` in the `Barion` constructor (in this case, `describe` wouldn't have called).

But anyway, I do not recommend to handle payment transactions in the client side, as it is so *insecure*. Everybody who download your app can view your secret POSKey, and with it, they can use Barion API in your behalf.

Instead of handling transactions in client side, you must write your own server-side logic for it. Client must send cart data to your server over HTTPS. On server-side, you should initiate a payment with the help of `node-barion`, and send back the payment gateway URL to the client as a response.

**Comment by aron123** [comment]
Please reopen, if you have any more questions.
